trigger:
  branches:
    include:
      - Dev

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: auth_service
  dockerRegistryServiceConnection: az-acr
  tag: $(Build.BuildId)

steps:

- checkout: self

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    repository: $(imageRepository)
    Dockerfile: Dockerfile
    tags: |
      $(tag)

- script: |
    sudo apt-get update
    sudo apt-get install -y wget

    wget https://github.com/aquasecurity/trivy/releases/download/v0.71.0/trivy_0.71.0_Linux-64bit.deb

    sudo dpkg -i trivy_0.71.0_Linux-64bit.deb
  displayName: Install Trivy

- script: |
    trivy image \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      auth_service:$(Build.BuildId)
  displayName: Trivy Scan

- task: Docker@2
  displayName: Push Image
  inputs:
    command: buildAndPush
    repository: $(imageRepository)

    containerRegistry: $(dockerRegistryServiceConnection)

    Dockerfile: Dockerfile

    tags: |
      $(tag)
      latest