trigger: none

pr: none

resources:
  pipelines:
    - pipeline: ci
      source: Ecommerce_auth_ci_pipeline
      trigger: true

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Deploy
    displayName: Deploy Application

    jobs:
      - deployment: DeployAuthService
        displayName: Deploy Auth Service
        environment: ecommerce-dev

        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - download: ci
                  artifact: image-tag

                - script: |
                    pwd
                    echo "================="
                    ls -R
                  displayName: Debug Files

                - script: |
                    IMAGE=$(cat $(Pipeline.Workspace)/ci/image-tag/image-tag.txt)

                    echo "Image = $IMAGE"

                    echo "##vso[task.setvariable variable=IMAGE_NAME]$IMAGE"
                  displayName: Read Image Reference

                - script: |
                    BRANCH="$(resources.pipeline.ci.sourceBranch)"

                    echo "Triggered from branch: $BRANCH"

                    if [ "$BRANCH" = "refs/heads/Dev" ]; then
                      NAMESPACE="ecommerce"
                    elif [ "$BRANCH" = "refs/heads/sandbox" ]; then
                      NAMESPACE="ecommerce-sb"
                    elif [ "$BRANCH" = "refs/heads/main" ]; then
                      NAMESPACE="ecommerce-prod"
                    else
                      echo "Unsupported branch: $BRANCH"
                      exit 1
                    fi

                    echo "Namespace = $NAMESPACE"

                    echo "##vso[task.setvariable variable=NAMESPACE]$NAMESPACE"
                  displayName: Set Namespace Based On Branch

                - script: |
                    sed -i "s|IMAGE_PLACEHOLDER|$(IMAGE_NAME)|g" deploymentfile/auth-deployment.yaml

                    cat deploymentfile/auth-deployment.yaml
                  displayName: Replace Image

                # - task: Kubernetes@1
                #   displayName: Deploy External Secret
                #   inputs:
                #     connectionType: Kubernetes Service Connection
                #     kubernetesServiceEndpoint: kubernetes-sc
                #     namespace: $(NAMESPACE)
                #     command: apply
                #     arguments: -f deploymentfile/auth-external-secret.yaml

                - task: Kubernetes@1
                  displayName: Deploy Service
                  inputs:
                    connectionType: Kubernetes Service Connection
                    kubernetesServiceEndpoint: kubernetes-sc
                    namespace: $(NAMESPACE)
                    command: apply
                    arguments: -f deploymentfile/auth-service.yaml

                # - task: Kubernetes@1
                #   displayName: Deploy Deployment
                #   inputs:
                #     connectionType: Kubernetes Service Connection
                #     kubernetesServiceEndpoint: kubernetes-sc
                #     namespace: $(NAMESPACE)
                #     command: apply
                #     arguments: -f deploymentfile/auth-deployment.yaml

                # - task: Kubernetes@1
                #   displayName: Verify Rollout
                #   inputs:
                #     connectionType: Kubernetes Service Connection
                #     kubernetesServiceEndpoint: kubernetes-sc
                #     namespace: $(NAMESPACE)
                #     command: rollout
                #     arguments: status deployment/auth-service --timeout=300s