apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: ecommerce
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:Satish19297@mongodb-service:27017/?authSource=admin"
  JWT_SECRET: "my_super_secret_key"