metadata:
  name: auth-service-sandbox
  namespace: sandbox

spec:
  replicas: 2

  template:
    spec:
      containers:
      - name: auth-service

        image: IMAGE_PLACEHOLDER

        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"

          limits:
            cpu: "1"
            memory: "1Gi"